-- Cities table
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE IF NOT EXISTS cities(
    id INT AUTO-INCREMENT PRIMARY KEY NOT NULL,
    state_id INT FOREIGN KEY NOT NULL,
    name VARCHAR(256) NOT NULL
)
